name: lazy_download
description: merged into lazy_ui_utils
version: 0.0.3
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  lazy_log: ^2.0.0
  # lazy_log:
  #   path: ../lazy_log

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
