name: lazy_extensions
description: Provide extensions and functions for various types to save time and efforts.
version: 1.0.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=2.17.6 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {intl: ^0.17.0}
