name: lazy_g_drive
description: A simple Google Drive Api package mainly design for AppData scope operation.
version: 2.1.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  googleapis: ^11.2.0
  lazy_extensions:
    git:
      url: https://github.com/Gunzilla-Games/flutter_lazy
      ref: main
      path: lazy_extensions
  lazy_http_client: ^2.0.0
  lazy_log: ^2.0.0
  # lazy_extensions:
  #   path: ../lazy_extensions
  # lazy_http_client:
  #   path: ../lazy_http_client
  # lazy_log:
  #   path: ../lazy_log

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
