name: lazy_collection
description: Intended to save time, especially from things that are very repetitive across projects.

version: 0.4.3
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  http: ^0.13.5
  intl: ^0.17.0
  lazy_log: ^1.0.4
  theme_provider: ^0.5.0
  universal_html: ^2.0.8
  url_launcher: ^6.1.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
