name: lazy_sign_in
description: Base package for [lazy_sign_in_extension] and [lazy_sign_in_google].

version: 1.0.3
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  lazy_log: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
