name: lazy_sign_in_google
description: '[google_sign_in] wrapper using [lazy_sign_in] interface. Support web and app Google sign in.'

version: 2.1.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  google_sign_in: ^6.1.4
  http: ^1.0.0
  js: ^0.6.5
  lazy_log: ^2.0.0
  lazy_sign_in: ^2.1.0
  # lazy_log:
  #   path: ../lazy_log
  # lazy_sign_in:
  #   path: ../lazy_sign_in

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
