name: lazy_sign_in_google
description: '[google_sign_in] wrapper using [lazy_sign_in] interface. Support web and app Google sign in.'

version: 1.1.1
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^5.4.1
  http: ^0.13.5
  js: ^0.6.4
  lazy_log: ^1.0.7
  lazy_sign_in: ^1.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

flutter:
  uses-material-design: true
