name: lazy_sign_in_extension
description: Chrome/Firefox extension Google sign-in library base on [LazySignIn]
version: 1.1.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5
  js: ^0.6.4
  lazy_log: ^1.0.4
  lazy_sign_in: ^1.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
