name: lazy_g_sync
description: Single file sync using Google Drive `appData` space. A bridge between [lazy.GDrive], [lazy.GSignIn] and local data/content.
version: 2.1.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  googleapis: ^11.2.0
  lazy_g_drive: ^2.0.0
  lazy_log: ^2.0.0
  lazy_extensions: ^2.0.0
  # lazy_extensions:
  #   path: ../lazy_extensions
  # lazy_g_drive:
  #   path: ../lazy_g_drive
  # lazy_log:
  #   path: ../lazy_log

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
