name: lazy_cache
description: Provides an indexed local storage on top of the shared_preferences package.
version: 1.0.2
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  json_preferences: ^1.0.2
  lazy_log: ^1.0.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
