name: lazy_http_client
description: Simple http client class that will auto apply specified headers on all request.

version: 1.0.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
